CREATE DATABASE DB_SECURITY;
USE DB_SECURITY;

CREATE TABLE TBL_MEMBER_AUTHORITY(
	M_AUTHORITY_NO INT NOT NULL AUTO_INCREMENT,
	M_AUTHORITY_ROLE_NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY(M_AUTHORITY_NO)
);

INSERT INTO TBL_MEMBER_AUTHORITY(M_AUTHORITY_ROLE_NAME) 
VALUES("USER");

SELECT * FROM TBL_MEMBER_AUTHORITY;
DROP TABLE TBL_MEMBER_AUTHORITY;

CREATE TABLE TBL_MEMBER(
	M_NO INT AUTO_INCREMENT NOT NULL,
	M_ID VARCHAR(20) NOT NULL UNIQUE,
	M_PW VARCHAR(100) NOT NULL,
	M_AUTHORITY_NO TINYINT NOT NULL DEFAULT 1,
	M_ISACCOUNTNONEXPIRED TINYINT NOT NULL DEFAULT 1, 		-- 만료되지 않은 계정
	M_ISACCOUNTNONLOCKED TINYINT NOT NULL DEFAULT 1,  		-- 계정이 잠기지 않음
	M_ISCREDENTIALSNONEXPIRED TINYINT NOT NULL DEFAULT 1, 	-- 만료되지 않은 자격 증명
	M_ISENABLED TINYINT NOT NULL DEFAULT 1, 				-- 활성화됨
	M_REG_DATE DATETIME DEFAULT NOW(),
	M_MOD_DATE DATETIME DEFAULT NOW(),
	PRIMARY KEY(M_NO)
);

SELECT * FROM TBL_MEMBER;
DROP TABLE TBL_MEMBER;

CREATE TABLE TBL_ADMIN_AUTHORITY(
	A_AUTHORITY_NO INT NOT NULL AUTO_INCREMENT,
	A_AUTHORITY_ROLE_NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY(A_AUTHORITY_NO)
);

INSERT INTO TBL_ADMIN_AUTHORITY(A_AUTHORITY_ROLE_NAME) 
VALUES("SUPER_ADMIN");
INSERT INTO TBL_ADMIN_AUTHORITY(A_AUTHORITY_ROLE_NAME) 
VALUES("SUB_ADMIN");

SELECT * FROM TBL_ADMIN_AUTHORITY;
DROP TABLE TBL_ADMIN_AUTHORITY;

CREATE TABLE TBL_ADMIN(
	A_NO INT AUTO_INCREMENT NOT NULL,
	A_ID VARCHAR(20) NOT NULL UNIQUE,
	A_PW VARCHAR(100) NOT NULL,
	A_AUTHORITY_NO TINYINT NOT NULL DEFAULT 1,
	A_ISACCOUNTNONEXPIRED TINYINT NOT NULL DEFAULT 1, 		-- 만료되지 않은 계정
	A_ISACCOUNTNONLOCKED TINYINT NOT NULL DEFAULT 1,  		-- 계정이 잠기지 않음
	A_ISCREDENTIALSNONEXPIRED TINYINT NOT NULL DEFAULT 1, 	-- 만료되지 않은 자격 증명
	A_ISENABLED TINYINT NOT NULL DEFAULT 1, 				-- 활성화됨
	A_REG_DATE DATETIME DEFAULT NOW(),
	A_MOD_DATE DATETIME DEFAULT NOW(),
	PRIMARY KEY(A_NO)
);

SELECT * FROM TBL_ADMIN;
DROP TABLE TBL_ADMIN;